spring.application.name=whylytics-server
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/whylytics
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=AIzaSyBtDEaUw9jqA6qQdKlx-FVlVBkKIw7HiVk